# 크롤링 가능한 종목 & url 임포트

In [20]:
import pandas as pd
url_list = pd.read_csv(u'.\분석코드\url_list.csv', encoding = 'utf-8')
url_list

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 47-48: truncated \uXXXX escape (<ipython-input-20-a98f0d9b9116>, line 2)

In [5]:
url_list.head()

   Unnamed: 0      name                                                url
0           0      삼성전자  http://search.mt.co.kr/searchNewsList.html?src...
1           1    SK하이닉스  http://search.mt.co.kr/searchNewsList.html?src...
2           2       현대차  http://search.mt.co.kr/searchNewsList.html?src...
3           3  삼성바이오로직스  http://search.mt.co.kr/searchNewsList.html?src...
4           4      셀트리온  http://search.mt.co.kr/searchNewsList.html?src...

In [10]:
url_list2 = url_list.set_index('name', drop = True)

In [11]:
url_list2

          Unnamed: 0                                                url
name
삼성전자               0  http://search.mt.co.kr/searchNewsList.html?src...
SK하이닉스             1  http://search.mt.co.kr/searchNewsList.html?src...
현대차                2  http://search.mt.co.kr/searchNewsList.html?src...
삼성바이오로직스           3  http://search.mt.co.kr/searchNewsList.html?src...
셀트리온               4  http://search.mt.co.kr/searchNewsList.html?src...
LG화학               5  http://search.mt.co.kr/searchNewsList.html?src...
POSCO              6  http://search.mt.co.kr/searchNewsList.html?src...
삼성물산               7  http://search.mt.co.kr/searchNewsList.html?src...
SK텔레콤              8  http://search.mt.co.kr/searchNewsList.html?src...
NAVER              9  http://search.mt.co.kr/searchNewsList.html?src...
한국전력              10  http://search.mt.co.kr/searchNewsList.html?src...
현대모비스             11  http://search.mt.co.kr/searchNewsList.html?src...
신한지주              12  http://search.mt.co.kr/searchNewsList.html?src...
KB금융              13  http://search.mt.co.kr/searchNewsList.html?src...
SK                14  http://search.mt.co.kr/searchNewsList.html?src...
삼성생명              15  http://search.mt.co.kr/searchNewsList.html?src...
LG생활건강            16  http://search.mt.co.kr/searchNewsList.html?src...
SK이노베이션           17  http://search.mt.co.kr/searchNewsList.html?src...
삼성에스디에스           18  http://search.mt.co.kr/searchNewsList.html?src...
삼성SDI             19  http://search.mt.co.kr/searchNewsList.html?src...
기아차               20  http://search.mt.co.kr/searchNewsList.html?src...
KT&G              21  http://search.mt.co.kr/searchNewsList.html?src...
LG                22  http://search.mt.co.kr/searchNewsList.html?src...
삼성화재              23  http://search.mt.co.kr/searchNewsList.html?src...
하나금융지주            24  http://search.mt.co.kr/searchNewsList.html?src...
S-Oil             25  http://search.mt.co.kr/searchNewsList.html?src...
LG전자              26  http://search.mt.co.kr/searchNewsList.html?src...
아모레퍼시픽            27  http://search.mt.co.kr/searchNewsList.html?src...
엔씨소프트             28  http://search.mt.co.kr/searchNewsList.html?src...
롯데케미칼             29  http://search.mt.co.kr/searchNewsList.html?src...
...              ...                                                ...
맥쿼리인프라            70  http://search.mt.co.kr/searchNewsList.html?src...
대한항공              71  http://search.mt.co.kr/searchNewsList.html?src...
한화케미칼             72  http://search.mt.co.kr/searchNewsList.html?src...
KCC               73  http://search.mt.co.kr/searchNewsList.html?src...
현대해상              74  http://search.mt.co.kr/searchNewsList.html?src...
두산밥캣              75  http://search.mt.co.kr/searchNewsList.html?src...
한국항공우주            76  http://search.mt.co.kr/searchNewsList.html?src...
쌍용양회              77  http://search.mt.co.kr/searchNewsList.html?src...
삼성엔지니어링           78  http://search.mt.co.kr/searchNewsList.html?src...
BGF리테일            79  http://search.mt.co.kr/searchNewsList.html?src...
삼성증권              80  http://search.mt.co.kr/searchNewsList.html?src...
호텔신라              81  http://search.mt.co.kr/searchNewsList.html?src...
현대엘리베이            82  http://search.mt.co.kr/searchNewsList.html?src...
유한양행              83  http://search.mt.co.kr/searchNewsList.html?src...
휠라코리아             84  http://search.mt.co.kr/searchNewsList.html?src...
오뚜기               85  http://search.mt.co.kr/searchNewsList.html?src...
GS리테일             86  http://search.mt.co.kr/searchNewsList.html?src...
메리츠종금증권           87  http://search.mt.co.kr/searchNewsList.html?src...
금호석유              88  http://search.mt.co.kr/searchNewsList.html?src...
제일기획              89  http://search.mt.co.kr/searchNewsList.html?src...
신세계               90  http://search.mt.co.kr/searchNewsList.html?src...
한화                91  http://search.mt.co.kr/searchNewsList.html?src...
현대미포조선            92  http://search.mt.co.kr/searchNewsList.html?src...
메리츠화재             93  http://search.mt.co.kr/searchNewsList.html?src...
대우건설              94  http://search.mt.co.kr/searchNewsList.html?src...
팬오션               95  http://search.mt.co.kr/searchNewsList.html?src...
오렌지라이프            96  http://search.mt.co.kr/searchNewsList.html?src...
포스코대우             97  http://search.mt.co.kr/searchNewsList.html?src...
현대로템              98  http://search.mt.co.kr/searchNewsList.html?src...
OCI               99  http://search.mt.co.kr/searchNewsList.html?src...

[100 rows x 2 columns]

# 새로운 데이터 전용 클래스

In [240]:
import pandas as pd
import numpy as np
import re
import pickle
from joblib import dump, load
import datetime
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_selection import chi2
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_selection import SelectKBest
from eunjeon import Mecab
mecab = Mecab()
count_vect = CountVectorizer()
TfidfTransformer()


# class 정의 => 기능은 뉴스랑 주가데이터 임포트 ~ 전처리데이터 익스포트
# filename : "news_all.csv"
# filepath : "./dataset/"
class stockcls():
    def get_smallnews(self, filename):
        df = pd.read_csv(filepath, encoding = 'utf-8 sig', engine = 'python')
        df['title+body'] = df.apply(lambda x : '{}|||{}'.format(x['TITLE'], x['BODY']), axis = 1) # title과 body 합쳐서 새로운 칼럼 추가  구분자 : |||
        df['title+body'] = df['title+body'].astype(str)
        df['NOUNS'] = df['title+body'].apply(lambda x : '{}'.format(mecab.nouns(x))) # ''씌워줘야 list 안 원소들이 join해서 붙는다.
        df.rename(columns={'TIME': 'Date'}, inplace = True)
        df = df.groupby('Date').agg({'NOUNS' : lambda x : ''.join(x)})
        df['Date'] = df['Date'].strftime("%Y.%m.%d")
        df = df['NOUNS']
        return df

    
    def get_prob(self, filename):
        # 분류모델과 전처리모델 불러와 저장
        with open(filename+'SVCmodel.pkl', 'rb') as f:
            clf_svc = pickle.load(f)
        with open(filename+'vec_feature.bin', 'rb') as f:
            vec_feature = pickle.load(f)
            

        # 전처리 피클파일에서 모델 불러와 저장
        vectorizer = vec_feature.get('vectorizer')
        selector = vec_feature.get('selector')
        
        
        X_new2_vec = vectorizer.transform(X_new2)
        X_new2_chi2 = selector.transform(X_new2_vec)
        
        
        predicted = clf_svc.predict(X_new2_chi2)
        predicted_probability = clf_svc.predict_proba(X_new2_chi2)
        return predicted, predicted_probability

### 분류할 데이터 Import & Cleansing

In [ ]:
# 인스턴스 생성
cls = data_import_preprocess()

X = df_news_stock_new['NOUNS']
X_new = cls.news_get('./small_news/삼성전자.csv')
X_new = X_new.groupby('Date').agg({'NOUNS' : lambda x : ''.join(x)})
X_new2 = X_new['NOUNS']
X_new2

### 모델 Import

In [ ]:
# 분류모델과 전처리모델 불러와 저장
with open('삼성전자SVCmodel.pkl', 'rb') as f:
    clf_svc = pickle.load(f)
with open('삼성전자vec_feature.bin', 'rb') as f:
    vec_feature = pickle.load(f)

# 전처리 피클파일에서 모델 불러와 저장
vectorizer = vec_feature.get('vectorizer')
selector = vec_feature.get('selector')

### 전처리

In [ ]:
X_new2_vec = vectorizer.transform(X_new2)
X_new2_chi2 = selector.transform(X_new2_vec)

### 분류 실행

In [ ]:
predicted = clf_svc.predict(X_new2_chi2)
predicted_probability = clf_svc.predict_proba(X_new2_chi2)

# 날짜 함수(2일전 날짜 파싱용)

In [282]:
from datetime import datetime, timedelta, date


def getday(n):
    n_day = timedelta(days=n)
    res =  date.today() - n_day
    end = res.strftime("%Y.%m.%d")
    return end


def gettoday():
    today = datetime.today().strftime("%Y.%m.%d")
    return today

# 3일치 뉴스로 분류해보기
- tfidf 에러 : https://stackoverflow.com/questions/44855780/idf-vector-is-not-fitted-error-when-using-a-saved-classifier-model?rq=1
- 피클 에러: http://thiagomarzagao.com/2015/12/08/saving-TfidfVectorizer-without-pickles/

In [92]:
# 인스턴스 생성
cls = data_import_preprocess()


X_new = cls.news_get('./small_news/삼성전자.csv')
X_new = cls.noun_extracting(df_news, mecab)
X_new = X_new.groupby('Date').agg({'NOUNS' : lambda x : ''.join(x)})

In [293]:
X_new

                                                        NOUNS
Date
2017-09-07  ['박근혜', '구속', '후', '선고', '가능', '추가', '영장', '발부...
2017-09-08  ['종목', '동종', '업계', '분석', '삼성전자', '농심', '개', '종...
2017-09-09  ['충남', '대', '학기', '취', '창업', '프로그램', '마련', '충남...
2017-09-10  ['美', '세탁기', '시장', '삼성', '월', '풀', '신경전', '달',...
2017-09-11  ['심', '징역', '년', '이재용', '재판부', '항소', '이유', '제출...
2017-09-12  ['김명수', '재벌', '양형', '공식', '생각', '김명수', '대법원장',...
2017-09-13  ['국정', '농단', '재판', '이재용', '일', '김기춘', '일', '시작...
2017-09-14  ['투자', '보고서', '끝', '추락', '지금', '바닥', '기아차', '피...
2017-09-15  ['특검', '정유라', '보쌈', '증언', '언급', '유감', '崔', '씨'...
2017-09-16  ['코스피', '외국인', '억', '원', '순매도', '마감', '월', '셋째...
2017-09-17  ['갤', '노트', '주말', '시장', '불법', '보조금', '급증', '과열...
2017-09-18  ['세계', '등', '한국', '기업', '증시', '동반', '사상', '최고'...
2017-09-19  ['이동', '통신', '유통', '완전', '자급', '문제', '고찰', '막무...
2017-09-20  ['경북', '지식', '재산', '센터', '나래', '프로그램', '인기', '...
2017-09-21  ['기업', '리포트', '년', '경제', '시사', '토크', '사이다', '기...
2017-09-22  ['내일', '장', '멘토링', '눈', '성장', '관심', '주', '스텍',...
2017-09-23  ['반도체', '株', '분전', '코스피', '북', '핵', '리스트', '상승...
2017-09-24  ['준비', '미래', '좌우', '삼성', '차', '혁명', '속도전', '美'...
2017-09-25  ['용인', '삼성', '워킹', '페스티벌', '만', '명', '용인시', '일...
2017-09-26  ['삼성', '하이닉스', '北', '리스크', '발목', '코스피', '외인', ...
2017-09-27  ['내일', '전략', '갈피', '코스피', '결국', '실적', '분기', '순...
2017-09-28  ['상생', '협력', '재현', '텍스', '인테리어', '업계', '친환경', ...
2017-09-29  ['박', '원오', '박근혜', '말', '거', '탄핵', '종합', '박상진'...
2017-09-30  ['홈', '최종', '전서', '경헌호', '김광삼', '코치', '퇴식', '트...
2017-10-01  ['단말기', '지원금', '상한', '폐지', '날', '갤', '노트', '이통...
2017-10-02  ['中', '최고', '인기', '스마트폰', '브랜드', '화웨이', '애플', ...
2017-10-03  ['하이닉스', '도시바', '투자', '최종', '계약', '변수', '웨스턴',...
2017-10-04  ['추석', '끝', '쇼핑', '시작', '코리아', '세일', '페스타', '완...
2017-10-05  ['베인', '도시바', '메모리', '수년', '내', '상장', '분쟁', '해...
2017-10-06  ['세탁기', '연방', '정부', '필요', '美', '언론', '반발', '종합...
...                                                       ...
2018-11-17  ['팟츠', '점', '전자', '랜드', '삼성', '연승', '삼성', '연패'...
2018-11-18  ['서브', '원', '부문', '매각', '협상', '대상자', '피너티', '선...
2018-11-19  ['기고', '스마트폰', '수요', '침체', '혁신', '스마트폰', '산업',...
2018-11-20  ['美', '증시', '급락', '코스피', '선', '후퇴', '거래일', '만'...
2018-11-21  ['굿모닝', '체크', '주', '급락', '본격', '조정', '진입', '신호...
2018-11-22  ['점', '포', '방', '유병훈', '생각', '창원', '세이', '커스',...
2018-11-23  ['영상', '반도체', '백혈병', '분쟁', '마침표', '년', '만', '고...
2018-11-25  ['美', '中', '무역', '협상', '기대감', '낙관', '경계', '주간'...
2018-11-26  ['코스피', '기관', '매수', '닷새', '반', '반', '등', '선', ...
2018-11-27  ['리포트', '삼성전자', '재량', '근로', '시행', '이유', '근로', ...
2018-11-28  ['中企', '기업', '다툼', '모', '비프', '렌', '파렴치한', '갑'...
2018-11-29  ['세계', '전쟁', '중', '한국', '미국', '중국', '일본', '선두'...
2018-11-30  ['삼성', '화웨이', '소송', '가능', '방법', '검토', '중', '중국...
2018-12-01  ['스마트폰', '월', '일', '시대', '개막', '진짜', '배', '이동'...
2018-12-02  ['삼성', '분기', '스마트폰', '위', '애플', '것', '삼성', '화웨...
2018-12-03  ['쿠폰', '만', '원', '할인', '車', '업계', '연말', '판촉', ...
2018-12-04  ['검찰', '압수수색', '증거', '인멸', '삼성', '위법', '증거', '...
2018-12-05  ['삼성', '에버랜드', '노조', '해', '경찰', '개입', '정황', '포...
2018-12-06  ['인사', '삼성전자', '사', '장단', '인사', '부회장', '승진', '...
2018-12-07  ['자동', '제설', '발열', '기능', '로고', '광고', '동시', '스노...
2018-12-09  ['코스피', '박스', '순환', '매', '예상', '대외', '여전', '주간...
2018-12-10  ['이재용', '인도', '통신', '재벌', '딸', '결혼식', '축하연', '...
2018-12-11  ['더블', '더블', '할로웨이', '펠프스', '승리', '우리', '인천', ...
2018-12-12  ['갤럭시', '이영희', '삼성전자', '부사장', '무선', '사업', '부',...
2018-12-13  ['내셔널', '피', '피이', '일', '금계', '찜', '닭', '회', '...
2018-12-14  ['국민주', '삼성전자', '배신', '주가', '만', '원', '붕괴', '실...
2018-12-15  ['해외', '역관', '삼성', '등', '민간', '전문가', '영입', '미국...
2018-12-16  ['시티', '건설', '강남', '역삼동', '시티', '프라', '강남', '분...
2018-12-17  ['부고', '박헌용', '씨', '이노베이션', '전략', '실장', '부친상',...
2018-12-18  ['삼성전자', '강경훈', '부사장', '일', '구속', '심사', '삼성', ...

[447 rows x 1 columns]

In [291]:
X_new2 = X_new.copy()

### 내일 예측을 위해 2일전 뉴스만 파싱  (2일전 -> 1일전 -> 0일전(오늘) ===>>> 내일 예측)

In [297]:
parse_day = getday(2)
X_new3 = X_new2.loc[parse_day:, 'NOUNS']

In [298]:
X_new3[]

Series([], Name: NOUNS, dtype: object)

In [299]:
parse_day

'2019.02.17'

In [295]:
X_new2.index = X_new2.index.strftime("%Y.%m.%d")

### SVC분류모델 임포트

In [272]:
clf_svc = pickle.load(open('SVCmodel_Ver1.pkl', 'rb'))

### 기존 모델이 모듈에 들어있어서 새로 벡터트랜스포머 다시 만듬

In [273]:
# X전체를 벡터화시킨 모델 기존
X_vec = count_vect.fit_transform(X)
tfidf_transformer = TfidfTransformer(use_idf = True).fit(X_vec)

### 만든 뒤 새로운 test데이터를 기존 트랜스포머에 넣고 벡터 추출

In [274]:
# X_new2만 다시 바꿔서 쏙 넣기
X_new2_vec = count_vect.transform(X_new2)
X_new2_tfidf = tfidf_transformer.transform(X_new2_vec)

### X_new2도 피처셀렉션 진행

In [275]:
X_new2_tfidf_chi2 = chi2_kbest.transform(X_new2_tfidf)

### 예측분류기에 넣기

In [276]:
predicted = clf_svc.predict(X_new2_tfidf_chi2)

In [277]:
predicted

array([-1, -1], dtype=int64)

In [281]:
df_news_stock_new.tail()

,NOUNS,Open,Close,day1T,day3T,day5T,day10T,Diff1,Diff3,Diff5,Diff10,Diff1_per,Diff3_per,Diff5_per,Diff10_per,Diff1_clf,Diff3_clf,Diff5_clf,Diff10_clf
Date,,,,,,,,,,,,,,,,,,,
2018-12-12,"['갤럭시', '이영희', '삼성전자', '부사장', '무선', '사업', '부',...",40250.0,40450.0,40000.0,39150.0,39100.0,38250.0,-450.0,-1300.0,-1350.0,-2200.0,-1.11,-3.21,-3.34,-5.44,-1,-1,-1,-1
2018-12-13,"['내셔널', '피', '피이', '일', '금계', '찜', '닭', '회', '...",40650.0,40000.0,38950.0,38900.0,38650.0,38700.0,-1050.0,-1100.0,-1350.0,-1300.0,-2.62,-2.75,-3.38,-3.25,-1,-1,-1,-1
2018-12-14,"['국민주', '삼성전자', '배신', '주가', '만', '원', '붕괴', '실...",40200.0,38950.0,39150.0,39100.0,38650.0,38750.0,200.0,150.0,-300.0,-200.0,0.51,0.39,-0.77,-0.51,1,1,-1,-1
2018-12-17,"['부고', '박헌용', '씨', '이노베이션', '전략', '실장', '부친상',...",38650.0,39150.0,38900.0,38650.0,38800.0,37600.0,-250.0,-500.0,-350.0,-1550.0,-0.64,-1.28,-0.89,-3.96,-1,-1,-1,-1
2018-12-18,"['삼성전자', '강경훈', '부사장', '일', '구속', '심사', '삼성', ...",38300.0,38900.0,39100.0,38650.0,38350.0,37450.0,200.0,-250.0,-550.0,-1450.0,0.51,-0.64,-1.41,-3.73,1,-1,-1,-1

# 벡터 추출기 import
- https://stackoverflow.com/questions/29788047/keep-tfidf-result-for-predicting-new-content-using-scikit-for-python

In [ ]:
#Load it later
transformer = TfidfTransformer()
loaded_vec = CountVectorizer(decode_error = "replace", vocabulary = pickle.load(open("이름.pkl", "rb")))
X_new2_tfidf = transformer.fit_transform(loaded_vec.fit_transform(X))

### chi2 Feature Selection 모델 import
- https://www.programcreek.com/python/example/93974/sklearn.feature_selection.SelectKBest

# 새로운거 시도하는 중

In [63]:
training_indices, validation_indices = training_indices, testing_indices = train_test_split(df.index, stratify = df_class, train_size=0.8, test_size=0.2)

In [64]:
from tpot import TPOTClassifier
from tpot import TPOTRegressor

tpot = TPOTClassifier(generations=5,verbosity=2)

tpot.fit(df.drop('Diff1_clf', axis=1).loc[training_indices].values,
         df.loc[training_indices, 'Diff1_clf'].values)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [74]:
df.dtypes

NOUNS          object
Diff1_clf    category
dtype: object

In [53]:
df_class = df_news_stock_new['Diff1_clf'].values

In [62]:
df = df_news_stock_new[['NOUNS', 'Diff1_clf']]

In [75]:
df['NOUNS'] = df['NOUNS'].astype('str')

C:\Users\sbg02\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,NOUNS,Open,Close,day1T,day3T,day5T,day10T,Diff1,Diff3,Diff5,Diff10,Diff1_per,Diff3_per,Diff5_per,Diff10_per,Diff1_clf,Diff3_clf,Diff5_clf,Diff10_clf
Date,,,,,,,,,,,,,,,,,,,
2017-12-01,"['내년', '증시', '조정기', '대비', '자산', '배분', '펀드', '주...",50800.0,50840.0,51340.0,50020.0,52000.0,50620.0,500.0,-820.0,1160.0,-220.0,0.98,-1.61,2.28,-0.43,1,-1,1,-1
2017-12-04,"['투자자', '항의', '빗발', '모간', '스탠리', '삼성전자', '조정',...",50840.0,51340.0,51260.0,50740.0,51780.0,51200.0,-80.0,-600.0,440.0,-140.0,-0.16,-1.17,0.86,-0.27,-1,-1,1,-1
2017-12-05,"['종목', '오늘', '특징', '주', '내년', '기대', '하나', '투어'...",50600.0,51260.0,50020.0,52000.0,52100.0,51560.0,-1240.0,740.0,840.0,300.0,-2.42,1.44,1.64,0.59,-1,1,1,1
2017-12-06,"['서울대', '시흥', '캠', '삼성', '현대차', '자율', '주행', '연...",51260.0,50020.0,50740.0,51780.0,51320.0,49140.0,720.0,1760.0,1300.0,-880.0,1.44,3.52,2.60,-1.76,1,1,1,-1
2017-12-07,"['朴', '뇌물', '공범', '공방', '특검', '최순', '실', '공모',...",50040.0,50740.0,52000.0,52100.0,51060.0,49700.0,1260.0,1360.0,320.0,-1040.0,2.48,2.68,0.63,-2.05,1,1,1,-1
2017-12-08,"['국정', '농단', '김종', '심', '징역', '년', '판결', '불복',...",51360.0,52000.0,51780.0,51320.0,50620.0,48200.0,-220.0,-680.0,-1380.0,-3800.0,-0.42,-1.31,-2.65,-7.31,-1,-1,-1,-1
2017-12-11,"['삼성', '반도체', '기술', '유출', '경쟁사', '협력', '업체', '...",52000.0,51780.0,52100.0,51060.0,51200.0,49360.0,320.0,-720.0,-580.0,-2420.0,0.62,-1.39,-1.12,-4.67,1,-1,-1,-1
2017-12-12,"['약국', '종이', '처방전', '대형', '병원', '종이', '처방전', '...",51820.0,52100.0,51320.0,50620.0,51560.0,50960.0,-780.0,-1480.0,-540.0,-1140.0,-1.50,-2.84,-1.04,-2.19,-1,-1,-1,-1
2017-12-13,"['삼성제약', '삼성제약', '헬스', '케어', '상표', '등록', '재추진'...",52100.0,51320.0,51060.0,51200.0,49140.0,51020.0,-260.0,-120.0,-2180.0,-300.0,-0.51,-0.23,-4.25,-0.58,-1,-1,-1,-1
2017-12-14,"['국정', '농단', '시작', '끝', '최순', '실', '재판', '구속',...",51320.0,51060.0,50620.0,51560.0,49700.0,51620.0,-440.0,500.0,-1360.0,560.0,-0.86,0.98,-2.66,1.10,-1,1,-1,1
2017-12-15,"['부고', '송창영', '씨', '법무법인', '세한', '변호사', '부친상',...",51240.0,50620.0,51200.0,49140.0,48200.0,51080.0,580.0,-1480.0,-2420.0,460.0,1.15,-2.92,-4.78,0.91,1,-1,-1,1
2017-12-18,"['주가', '반', '토막', '난', '삼성', '중공업', '증권사', '뉴스...",50620.0,51200.0,51560.0,49700.0,49360.0,52120.0,360.0,-1500.0,-1840.0,920.0,0.70,-2.93,-3.59,1.80,1,-1,-1,1
2017-12-19,"['배당', '계절', '개인', '접근', '배당주', '투자', '고배', '수...",51540.0,51560.0,49140.0,48200.0,50960.0,52020.0,-2420.0,-3360.0,-600.0,460.0,-4.69,-6.52,-1.16,0.89,-1,-1,-1,1
2017-12-21,"['공정위', '삼성물산', '합병', '가이드라인', '개정', '논란', '년'...",51000.0,49140.0,49700.0,49360.0,51020.0,50400.0,560.0,220.0,1880.0,1260.0,1.14,0.45,3.83,2.56,1,1,1,1
2017-12-22,"['스팟', '삼성전자', '만', '원', '만', '원', '출발', '일', ...",49400.0,49700.0,48200.0,50960.0,51620.0,48840.0,-1500.0,1260.0,1920.0,-860.0,-3.02,2.54,3.86,-1.73,-1,1,1,-1
2017-12-26,"['결국', '불발', '김종', '박원', '오', '증인', '신문', '플',...",49760.0,48200.0,49360.0,51020.0,51080.0,48240.0,1160.0,2820.0,2880.0,40.0,2.41,5.85,5.98,0.08,1,1,1,1
2017-12-27,"['전문', '이재용', '삼성전자', '부회장', '최후', '변론', '전문',...",48960.0,49360.0,50960.0,51620.0,52120.0,48200.0,1600.0,2260.0,2760.0,-1160.0,3.24,4.58,5.59,-2.35,1,1,1,-1
2017-12-28,"['내일', '장', '멘토링', '대형', '반도체', '주가', '주도', '년...",49560.0,50960.0,51020.0,51080.0,52020.0,48540.0,60.0,120.0,1060.0,-2420.0,0.12,0.24,2.08,-4.75,1,1,1,-1
2018-01-02,"['내일', '장', '멘토링', '올해', '증시', '신', '新', '고', ...",51380.0,51020.0,51620.0,52120.0,50400.0,50000.0,600.0,1100.0,-620.0,-1020.0,1.18,2.16,-1.22,-2.00,1,1,-1,-1
2018-01-03,"['정', '재계', '인사', '명', '자리', '올해', '변화', '단추',...",52540.0,51620.0,51080.0,52020.0,48840.0,49620.0,-540.0,400.0,-2780.0,-2000.0,-1.05,0.77,-5.39,-3.87,-1,1,-1,-1
2018-01-04,"['국정원', '뇌물', '혐의', '개', '박근혜', '형량', '심', '재판...",52120.0,51080.0,52120.0,50400.0,48240.0,49900.0,1040.0,-680.0,-2840.0,-1180.0,2.04,-1.33,-5.56,-2.31,1,-1,-1,-1
2018-01-05,"['오늘', '장', '터리', '닝', '시즌', '월', '효과', '종목', ...",51300.0,52120.0,52020.0,48840.0,48200.0,49320.0,-100.0,-3280.0,-3920.0,-2800.0,-0.19,-6.29,-7.52,-5.37,-1,-1,-1,-1
2018-01-08,"['최순', '실', '신동빈', '심', '선고', '내달', '일', '연기',...",52400.0,52020.0,50400.0,48240.0,48540.0,48240.0,-1620.0,-3780.0,-3480.0,-3780.0,-3.11,-7.27,-6.69,-7.27,-1,-1,-1,-1
2018-01-09,"['중국', '굴기', '한국', '참가', '개', '사', '중', '분', '...",51460.0,50400.0,48840.0,48200.0,50000.0,49160.0,-1560.0,-2200.0,-400.0,-1240.0,-3.10,-4.37,-0.79,-2.46,-1,-1,-1,-1
2018-01-10,"['한국', '블록체인', '협회', '초대', '회장', '진대제', '前', '...",50500.0,48840.0,48240.0,48540.0,49620.0,49340.0,-600.0,-300.0,780.0,500.0,-1.23,-0.61,1.60,1.02,-1,-1,1,1
2018-01-11,"['내일', '장', '멘토링', '가상', '폐주', '리스크', '관리', '시...",48200.0,48240.0,48200.0,50000.0,49900.0,50260.0,-40.0,1760.0,1660.0,2020.0,-0.08,3.65,3.44,4.19,-1,1,1,1
2018-01-12,"['종목', '오늘', '특징', '주', '증권', '주', '삼립', '엔', ...",48240.0,48200.0,48540.0,49620.0,49320.0,50780.0,340.0,1420.0,1120.0,2580.0,0.71,2.95,2.32,5.35,1,1,1,1
2018-01-15,"['영진', '전문대', '년', '연속', '상회', '취업률', '달성', '영...",48800.0,48540.0,50000.0,49900.0,48240.0,51220.0,1460.0,1360.0,-300.0,2680.0,3.01,2.80,-0.62,5.52,1,1,-1,1
2018-01-16,"['일', '복귀', '라틀리프', '경기', '감각', '서울', '삼성', '썬...",48760.0,50000.0,49620.0,49320.0,49160.0,49800.0,-380.0,-680.0,-840.0,-200.0,-0.76,-1.36,-1.68,-0.40,-1,-1,-1,-1
2018-01-17,"['년', '내', '매출액', '배', '삼성전자', '아프리카', '시장', '...",50020.0,49620.0,49900.0,48240.0,49340.0,49900.0,280.0,-1380.0,-280.0,280.0,0.56,-2.78,-0.56,0.56,1,-1,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-11-07,"['수급', '이상준', '소장', '메리', '증권', '수급', '분기', '실...",43600.0,44000.0,44050.0,45200.0,44100.0,42100.0,50.0,1200.0,100.0,-1900.0,0.11,2.73,0.23,-4.32,1,1,1,-1
2018-11-08,"['베일', '벗', '삼성', '폴', '더블', '폰', '차세대', '혁신',...",44900.0,44050.0,44300.0,44500.0,44250.0,42450.0,250.0,450.0,200.0,-1600.0,0.57,1.02,0.45,-3.63,1,1,1,-1
2018-11-09,"['김', '앤', '장', '교체', '증시', '무덤덤', '코스피', '하락'...",44450.0,44300.0,45200.0,44100.0,44000.0,42400.0,900.0,-200.0,-300.0,-1900.0,2.03,-0.45,-0.68,-4.29,1,-1,-1,-1
2018-11-12,"['리포트', '역대', '최대', '상속세', '교보', '조세', '불복', '...",43850.0,45200.0,44500.0,44250.0,43650.0,42600.0,-700.0,-950.0,-1550.0,-2600.0,-1.55,-2.10,-3.43,-5.75,-1,-1,-1,-1
2018-11-13,"['징역', '년', '항소심', '전략', '이학수', '증인', '신청', '검...",43900.0,44500.0,44100.0,44000.0,42800.0,43050.0,-400.0,-500.0,-1700.0,-1450.0,-0.90,-1.12,-3.82,-3.26,-1,-1,-1,-1
2018-11-14,"['삼성전자', '등기', '이사', '분기', '평균', '보수', '억', '원...",44500.0,44100.0,44250.0,43650.0,42100.0,43150.0,150.0,-450.0,-2000.0,-950.0,0.34,-1.02,-4.54,-2.15,1,-1,-1,-1
2018-11-15,"['삼성전자', '중국', '시장', '공략', '토털', '솔', '션', '제공...",44050.0,44250.0,44000.0,42800.0,42450.0,43150.0,-250.0,-1450.0,-1800.0,-1100.0,-0.56,-3.28,-4.07,-2.49,-1,-1,-1,-1
2018-11-16,"['中', '마이크', '삼성', '하이닉스', '조사', '진전', '반독점', ...",44600.0,44000.0,43650.0,42100.0,42400.0,41850.0,-350.0,-1900.0,-1600.0,-2150.0,-0.80,-4.32,-3.64,-4.89,-1,-1,-1,-1
2018-11-19,"['기고', '스마트폰', '수요', '침체', '혁신', '스마트폰', '산업',...",44050.0,43650.0,42800.0,42450.0,42600.0,43250.0,-850.0,-1200.0,-1050.0,-400.0,-1.95,-2.75,-2.41,-0.92,-1,-1,-1,-1
2018-11-20,"['美', '증시', '급락', '코스피', '선', '후퇴', '거래일', '만'...",42450.0,42800.0,42100.0,42400.0,43050.0,42150.0,-700.0,-400.0,250.0,-650.0,-1.64,-0.93,0.58,-1.52,-1,-1,1,-1
2018-11-21,"['굿모닝', '체크', '주', '급락', '본격', '조정', '진입', '신호...",41800.0,42100.0,42450.0,42600.0,43150.0,41450.0,350.0,500.0,1050.0,-650.0,0.83,1.19,2.49,-1.54,1,1,1,-1
2018-11-22,"['점', '포', '방', '유병훈', '생각', '창원', '세이', '커스',...",42000.0,42450.0,42400.0,43050.0,43150.0,40500.0,-50.0,600.0,700.0,-1950.0,-0.12,1.41,1.65,-4.59,-1,1,1,-1
2018-11-23,"['영상', '반도체', '백혈병', '분쟁', '마침표', '년', '만', '고...",42450.0,42400.0,42600.0,43150.0,41850.0,40950.0,200.0,750.0,-550.0,-1450.0,0.47,1.77,-1.30,-3.42,1,1,-1,-1
2018-11-26,"['코스피', '기관', '매수', '닷새', '반', '반', '등', '선', ...",42150.0,42600.0,43050.0,43150.0,43250.0,40200.0,450.0,550.0,650.0,-2400.0,1.06,1.29,1.53,-5.63,1,1,1,-1
2018-11-27,"['리포트', '삼성전자', '재량', '근로', '시행', '이유', '근로', ...",42900.0,43050.0,43150.0,41850.0,42150.0,40250.0,100.0,-1200.0,-900.0,-2800.0,0.23,-2.79,-2.09,-6.50,1,-1,-1,-1
2018-11-28,"['中企', '기업', '다툼', '모', '비프', '렌', '파렴치한', '갑'...",42800.0,43150.0,43150.0,43250.0,41450.0,40450.0,0.0,100.0,-1700.0,-2700.0,0.00,0.23,-3.94,-6.26,-1,1,-1,-1
2018-11-29,"['세계', '전쟁', '중', '한국', '미국', '중국', '일본', '선두'...",43850.0,43150.0,41850.0,42150.0,40500.0,40000.0,-1300.0,-1000.0,-2650.0,-3150.0,-3.01,-2.32,-6.14,-7.30,-1,-1,-1,-1
2018-11-30,"['삼성', '화웨이', '소송', '가능', '방법', '검토', '중', '중국...",43450.0,41850.0,43250.0,41450.0,40950.0,38950.0,1400.0,-400.0,-900.0,-2900.0,3.35,-0.96,-2.15,-6.93,1,-1,-1,-1
2018-12-03,"['쿠폰', '만', '원', '할인', '車', '업계', '연말', '판촉', ...",42750.0,43250.0,42150.0,40500.0,40200.0,39150.0,-1100.0,-2750.0,-3050.0,-4100.0,-2.54,-6.36,-7.05,-9.48,-1,-1,-1,-1
2018-12-04,"['검찰', '압수수색', '증거', '인멸', '삼성', '위법', '증거', '...",42650.0,42150.0,41450.0,40950.0,40250.0,38900.0,-700.0,-1200.0,-1900.0,-3250.0,-1.66,-2.85,-4.51,-7.71,-1,-1,-1,-1
2018-12-05,"['삼성', '에버랜드', '노조', '해', '경찰', '개입', '정황', '포...",40900.0,41450.0,40500.0,40200.0,40450.0,39100.0,-950.0,-1250.0,-1000.0,-2350.0,-2.29,-3.02,-2.41,-5.67,-1,-1,-1,-1
2018-12-06,"['인사', '삼성전자', '사', '장단', '인사', '부회장', '승진', '...",40600.0,40500.0,40950.0,40250.0,40000.0,38650.0,450.0,-250.0,-500.0,-1850.0,1.11,-0.62,-1.23,-4.57,1,-1,-1,-1
2018-12-07,"['자동', '제설', '발열', '기능', '로고', '광고', '동시', '스노...",40900.0,40950.0,40200.0,40450.0,38950.0,38650.0,-750.0,-500.0,-2000.0,-2300.0,-1.83,-1.22,-4.88,-5.62,-1,-1,-1,-1
2018-12-10,"['이재용', '인도', '통신', '재벌', '딸', '결혼식', '축하연', '...",40450.0,40200.0,40250.0,40000.0,39150.0,38800.0,50.0,-200.0,-1050.0,-1400.0,0.12,-0.50,-2.61,-3.48,1,-1,-1,-1
2018-12-11,"['더블', '더블', '할로웨이', '펠프스', '승리', '우리', '인천', ...",40600.0,40250.0,40450.0,38950.0,38900.0,38350.0,200.0,-1300.0,-1350.0,-1900.0,0.50,-3.23,-3.35,-4.72,1,-1,-1,-1
2018-12-12,"['갤럭시', '이영희', '삼성전자', '부사장', '무선', '사업', '부',...",40250.0,40450.0,40000.0,39150.0,39100.0,38250.0,-450.0,-1300.0,-1350.0,-2200.0,-1.11,-3.21,-3.34,-5.44,-1,-1,-1,-1
2018-12-13,"['내셔널', '피', '피이', '일', '금계', '찜', '닭', '회', '...",40650.0,40000.0,38950.0,38900.0,38650.0,38700.0,-1050.0,-1100.0,-1350.0,-1300.0,-2.62,-2.75,-3.38,-3.25,-1,-1,-1,-1
2018-12-14,"['국민주', '삼성전자', '배신', '주가', '만', '원', '붕괴', '실...",40200.0,38950.0,39150.0,39100.0,38650.0,38750.0,200.0,150.0,-300.0,-200.0,0.51,0.39,-0.77,-0.51,1,1,-1,-1
2018-12-17,"['부고', '박헌용', '씨', '이노베이션', '전략', '실장', '부친상',...",38650.0,39150.0,38900.0,38650.0,38800.0,37600.0,-250.0,-500.0,-350.0,-1550.0,-0.64,-1.28,-0.89,-3.96,-1,-1,-1,-1
2018-12-18,"['삼성전자', '강경훈', '부사장', '일', '구속', '심사', '삼성', ...",38300.0,38900.0,39100.0,38650.0,38350.0,37450.0,200.0,-250.0,-550.0,-1450.0,0.51,-0.64,-1.41,-3.73,1,-1,-1,-1

In [31]:
df_news_stock_new.drop(df_news_stock_new.columns['Open', 'Close', 'day1T', 'day3T', 'day5T', 'day10T', 'Diff1',
       'Diff3', 'Diff5', 'Diff10', 'Diff1_per', 'Diff3_per', 'Diff5_per',
       'Diff10_per'], axis=1, inplace=True)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [32]:
df_news_stock_new.drop(['Open', 'Close', 'day1T', 'day3T', 'day5T', 'day10T', 'Diff1',
       'Diff3', 'Diff5', 'Diff10', 'Diff1_per', 'Diff3_per', 'Diff5_per',
       'Diff10_per'], axis=1, inplace=True)

In [34]:
del df_news_stock_new['Date']

KeyError: 'Date'

# 3-2. 통계분류로 예측(svc, NaiveBaysian)
## Vectorization => Doc2Vec으로 학습

## 테스트 실행3 - Doc2Vec + Kernel SVM 분류기

In [7]:
vec = Vector()
clf = classification()

# 모델 임포트하는데 시간 좀 걸립니다. ㅠ / 모델 합치면 6G정도, 웬만한 노트북은 디스크 긁으면서 돌아갑니다.
model = vec.Doc_model_import('./Doc2VecClf/doc2vec_no_pos_tagging.model')

# 함수에 모델 넣는것도 오래걸린다 ㅠ
X_train, X_test, y_train, y_test = vec.Doc_vector(model, df_news_stock_new, n = '5', ratio = 0.2)

뽑아낸 Vector 크기 : 253

In [8]:
X_train, X_test, y_train, y_test = vec.Doc_vector(model, df_news_stock_new, n = '10', ratio = 0.2)

뽑아낸 Vector 크기 : 253

In [9]:
vec = Vector()
clf = classification()

svc = clf.SVC_tfidf(X_train, X_test, y_train, y_test)

훈련 셋 검증결과 : 1.000.
테스트 셋 검증결과 : 0.627.
[-1 -1  1  1  1  1 -1  1 -1 -1 -1 -1 -1  1  1 -1  1  1 -1 -1  1 -1  1 -1
 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1
 -1  1 -1 -1 -1  1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1  1  1  1 -1  1 -1
  1  1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1  1 -1 -1 -1  1 -1  1 -1
  1  1 -1 -1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1  1  1  1 -1  1  1  1  1 -1
 -1  1  1 -1 -1 -1 -1 -1  1 -1  1 -1  1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1
  1 -1  1 -1  1 -1 -1 -1  1 -1  1 -1 -1  1 -1 -1 -1  1 -1  1 -1 -1  1 -1
 -1  1 -1  1  1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1  1 -1 -1 -1  1
 -1  1 -1 -1  1  1 -1  1 -1 -1]

C:\Users\sbg02\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [10]:
!pip show gensim

Name: gensim
Version: 3.7.0
Summary: Python framework for fast Vector Space Modelling
Home-page: http://radimrehurek.com/gensim
Author: Radim Rehurek
Author-email: me@radimrehurek.com
License: LGPLv2.1
Location: c:\users\sbg02\anaconda3\lib\site-packages
Requires: six, smart-open, numpy, scipy
Required-by:

## 테스트 실행4 - Doc2Vec + Naive Baysian 분류기
- 코드는 이상 없는데, doc2vec에서 벡터를 추출하면 음수값이 섞여있으서 분류기 학습이 안된다.ㅠ

In [ ]:
vec = Vector()
clf = classification()

svc = clf.NB_tfidf(X_train, X_test, y_train, y_test)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
#count_vect = CountVectorizer()


# 파이프라인 쓰는법도 고려해보자!!!! 더 쉽고 간결함
# 시각화 함수도 넣으면 좋읗듯? 
class VectorFeature():
    
    def split_vectorize(self, df, n, ratio):
        # DataFrame에서 필요한 칼럼추출 => split
        X = df['NOUNS']
        y = df.loc[:, ['Diff'+n+'_clf']]
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = ratio)
        
        
        # 벡터화+tf/idf 해주는 pipeline 설계
        makevector = Pipeline([
            ('vect', CountVectorizer()),
            ('tfidf', TfidfTransformer()),
        ])
        
                
        # 벡터화 진행 후 저장(X_data만  실시)
        X_train_vec = makevector(X_train)
        X_test_vec = makevector(X_test)
        return X_train_vec, X_test_vec, y_train, y_test
    
    
    # k =15000정도 괜춘
    def feature_Select(self, X_train_vec, X_test_vec, y_train, y_test, k):
        # X벡터를 y값과 비교해 카이제곱검정으로 벡터 축소
        X_train_chi2 = SelectKBest(chi2, k = k).fit_transform(X_train_vec, y_train)
        X_test_chi2 = SelectKBest(chi2, k = k).fit_transform(X_test_vec, y_test)
        print(X_train_chi2.shape)
        print(X_test_chi2.shape)
        return X_train_chi2, X_test_chi2
    
    
''' 위 함수에 메소드 오버라이딩해보면 좋을 듯?
    super().feature_Select(X_train_vec, y,  k)   이렇게...?


    # k =15000정도 괜춘
    def feature_Select(self, X_train_vec, X_test_vec, y_train, y_test, k):
        # X벡터를 y값과 비교해 카이제곱검정으로 벡터 축소
        X_train_chi2 = SelectKBest(chi2, k = k).fit_transform(X_train_vec, y_train)
        X_test_chi2 = SelectKBest(chi2, k = k).fit_transform(X_test_vec, y_test)
        print(X_train_chi2.shape)
        print(X_test_chi2.shape)
        return X_train_chi2, X_test_chi2
'''
    
class classification(VectorFeature): 
    
    def NB_tfidf(self, X_train_vec, X_test_vec, y_train, y_test):
        MultinomialNB(alpha = 1.0, class_prior = None, fit_prior = True)
        clf_nb = MultinomialNB()
        clf_nb.fit(X_train_vec, y_train)
        
        #predicted = clf_tfidf.predict(X_test_vec)
        #print('tfidf로 변환한 예측률 :',np.mean(predicted == y_test))
        
        print('훈련 셋 검증결과 : {:.3f}.'.format(clf_nb.score(X_train, y_train)))
        print('테스트 셋 검증결과 : {:.3f}.'.format(clf_nb.score(X_test, y_test)))
        #print('UP/Down 예측값 : {:.3f}.'.format(clf_nb.predict_proba(X_test)))  만드는 중
        print(clf_nb.predict(X_train))
        

    # [과제]gamma는 0.1 / c는 10 디폴트로 설정해보자
    # 1param - Xdata / 2param - ydata / 3param - ratio / 4param - N일 뒤 예측(1,3,5,10)
    def SVC_tfidf(self, X_train_vec, X_test_vec, y_train, y_test):  # ratio - 0.2 / gamma - 0.1 / c - 10 디폴트하거나 파라미터 삭제
        clf_svc = SVC(gamma = 0.1, class_weight = "balanced", kernel = 'rbf', C = 10)
        clf_svc.fit(X_train_vec, y_train)
        
        print('훈련 셋 검증결과 : {:.3f}.'.format(clf_svc.score(X_train_vec, y_train)))
        print('테스트 셋 검증결과 : {:.3f}.'.format(clf_svc.score(X_test_vec, y_test)))
        #print(clf_svc.predict_proba(X_test))
        print(clf_svc.predict(X_train))
    
    
        # 퍼센트 안내멘트를 리턴하면 될듯?

In [ ]:
    # param1 - data / param2 - testSet 비율
    # X_train과 X_test만 벡터화시키면 된다. y는 그냥 칼럼 슬라이싱만 하면 ok(아직은 y값 2진분류)
    def split_vectorize(df, ratio):        
        # Train data 벡터 + tf/idf
        X_train_counts = count_vect.fit_transform(X) 
        tfidf_transformer = TfidfTransformer(use_idf=True).fit(X_train_counts) 
        X_train_tfidf = tfidf_transformer.transform(X_train_counts)
        
        # Test data 벡터 + tf/idf
        X_test_counts = count_vect.transform(X)
        X_test_tfidf = tfidf_transformer.transform(X_test_counts)

        return (X_train_tfidf, X_test_tfidf, y_train, y_test)
        
    # 아직 y슬라이싱 안하고 집어넣음 =-> 수정 보완 ㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱ 
    def NB_tfidf(df):
        clf_train = MultinomialNB().fit(X_train_tfidf, y_train)
        predicted_train = clf_tfidf.predict(X_train_tfidf)
        print('======== Train데이터 예측률 ========')
        print('tfidf로 변환한 예측률 :', np.mean(predicted_train == y_train))
        
        clf_test = MultinomialNB().fit(X_test_tfidf, y_test)
        print('======== Test데이터 예측률 ========')
        print('tfidf로 변환한 예측률 :', np.mean(clf_test == y_test))
        return 뭘 뽑아야 할까요`~?